[build]
  publish = "frontend"
  command = "echo 'No build needed - static frontend only'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Note: This is frontend-only deployment
# Backend APIs will need to be hosted elsewhere (Heroku, Railway, etc.)